Remove Compression/Decompression Overhead from RLPMemo
NethermindEth/Paprika pull request #456
Opened 2024-12-26 06:26 UTC by dipkakwani

2025-01-02 11:10 UTC, Scooletz requested changes
I think I either don't follow or there's a mistake in the approach of removing the `Compress`.

Let's assume that we have a `Branch` that has the children with the following first nibbles `{A, B, C}`. How does this approach distinguish cases where:

1. `A` and `B` are encoded to `Keccak` while `C` RLP is less than 31 bytes
2  `A` and `C` are encoded to `Keccak` while `B` RLP is less than 31 bytes

Where is the information stored now?

2025-01-02 11:10 UTC, Scooletz commented on src/Paprika/Merkle/RlpMemo.cs
> +        if (_buffer.Length == 0 || ((ushort)children & (1U << nibble)) == 0)
Does it effectively check whether the child is set in children? If yes, isn't it `RlpMemo` agnostic and `NibbleSet.Readonly[nibble]` could be used directly in the call site? Then, have this method removed?

2025-01-02 11:10 UTC, Scooletz commented on src/Paprika/Merkle/RlpMemo.cs
> +        var leftChildren = (ushort)((ushort)children & ((1U << (nibble + 1)) - 1));
Use counters in the children maybe? `SetCountBefore` or whatever it was named?

2025-01-02 11:10 UTC, Scooletz commented on src/Paprika/Merkle/ComputeMerkleBehavior.cs
> +                            memo = RlpMemo.Insert(memo, i, branch.Children, keccakOrRlp.Span, rlpMemoization);
What happens if encoded data in are not a `Keccak`? Do we store a `Keccak.Zero` then? If not, how does it distinguish between existence of a keccak or not? Doesn't it mean that RlpMemo requires a similar NibbleSet to store bits of what was remembered or not?

2025-01-06 09:37 UTC, Scooletz requested changes
A few remarks, but almost ready to merge.

2025-01-06 09:37 UTC, Scooletz commented on src/Paprika/Merkle/RlpMemo.cs
> +    private void GetIndex(out NibbleSet.Readonly index)
The `NibbleSet.Readonly` is only 2 bytes long. Have you considered returning it by value?

2025-01-06 09:37 UTC, Scooletz commented on src/Paprika/Merkle/RlpMemo.cs
> +            var bits = _buffer[^indexLength..];
This might be a nitpicking, but if we stored the index at the beginning, no span slice would be required and we could get it from the start, just by passing the buffer.

2025-01-06 09:37 UTC, Scooletz commented on src/Paprika/Merkle/RlpMemo.cs
> +            Debug.Assert(_buffer.Length is 0 or MaxSize);
```suggestion
            Debug.Assert(_buffer.Length is 0 or MaxSize, "Only empty or full RlpMemo can have no index");
```

2025-01-06 09:37 UTC, Scooletz commented on src/Paprika/Merkle/RlpMemo.cs
> +        Debug.Assert(!index[nibble]);
Turn comment into the debug message maybe?

2025-01-06 09:37 UTC, Scooletz commented on src/Paprika/Merkle/RlpMemo.cs
> +        var size = (index.SetCount < NibbleSet.NibbleCount - 1)
Size computation is repeated into multiple places. Why don't we extract it as a method? It'd be based on the number of destination nibbles set right? So a simple static method would do?

2025-01-06 09:37 UTC, Scooletz commented on src/Paprika/Merkle/RlpMemo.cs
> +        var size = (index.SetCount < NibbleSet.NibbleCount)
Again, use the extracted method?

2025-01-06 09:37 UTC, Scooletz commented on src/Paprika/Merkle/ComputeMerkleBehavior.cs
> +                        if (memo.Exists(i))
I like the clear approach here, where different cases are split.

2025-01-06 09:37 UTC, Scooletz commented on src/Paprika/Merkle/RlpMemo.cs
> -        if (children.SetCount == 2 && (key.Path.Length + key.StoragePath.Length) % 2 == 0)
This shaved off some memory for small branches. It wasn't the biggest saving but it did something. Is it intentionally removed?

2025-01-06 09:37 UTC, Scooletz commented on src/Paprika/Merkle/RlpMemo.cs
> -            var bits = leftover[^emptyBytesLength..];
We loose one compression opportunity here. Imagine a branch that has only one Keccak memoized in RlpMemo. In such a cache, we could encode this one on a single byte. Even more, we could encode up to 2 on a single byte. This would, for cases where only 1 or 2 keccaks are memoized, make them ligher by one byte. For 2 keccaks, it would be ~ 1.5% saving where for one it would be 3%. This would make it a bit more complicated though. Another option would be to treat the special case of 1 byte to keep the not-set (which would save some space for 15 and 14 set, but would be much less impactful size-wise I think).

I know that original decompress/compress had no such feature https://github.com/NethermindEth/Paprika/blob/61c326a39e942ab9c550f6a6b9b5df59e67c0f0f/src/Paprika/Merkle/RlpMemo.cs#L171-L176 but we use something similar for branches themselves https://github.com/NethermindEth/Paprika/blob/61c326a39e942ab9c550f6a6b9b5df59e67c0f0f/src/Paprika/Merkle/Node.cs#L405-L416

2025-01-06 09:37 UTC, Scooletz commented on src/Paprika.Tests/Merkle/RlpMemoTests.cs
> +    public void Random_delete()
The random tests are nice for fuzzying, but it would be beneficial to have some explicit A, B, C where A, B or A,C are set so that we cover what previously was missing. Or maybe I'm not seeing the tests like this but they do exist 👀

2025-01-10 07:54 UTC, dipkakwani commented on src/Paprika.Tests/Merkle/RlpMemoTests.cs
> +    public void Random_delete()
Yes, that test is missing but I am not quite sure how to capture this in the test - a child with Rlp < 31 bytes while others have keccaks?
I looked at existing tests to figure it out (e.g. `Three_accounts_sharing_start_nibble`, `Branch_two_leafs`), but I couldn't find a way to simulate this scenario:

```
[Test]
public void Insert_get_operation()
{
        var commit = new Commit();

        const string key0 = "A0000001";
        const string key1 = "B0000002";
        const string key2 = "C0000003";
        
        commit.Set(key0);
        commit.Set(key1);
        commit.Set(key2);
        
        NibbleSet.Readonly children = new NibbleSet(0xA, 0xB, 0xC);
        commit.SetBranch(Key.Merkle(NibblePath.Empty), children);

        var merkle = new ComputeMerkleBehavior();

        merkle.BeforeCommit(commit, CacheBudget.Options.None.Build());
}
```
I am probably missing some obvious way to complete this test scenario :face_with_diagonal_mouth:

2025-01-10 08:06 UTC, dipkakwani commented on src/Paprika/Merkle/RlpMemo.cs
> -            var bits = leftover[^emptyBytesLength..];
That's a good point! I was also thinking of another approach and wanted to run through you to check which one might be better (before completing the code changes): 
To maximum utilize one byte, it could store partial bitset index. We can basically divide the 2 bytes into two parts and utilize only 1 byte to represent the index for cases where multiple contiguous indices are set.

Original (2 bytes) : [0, 1, 2, .. 15]
Modified (1 Byte): [x, 0, 1, 2, 3, 4, 5, 6] or [x, 7, 8, 9, 10, 11, 12, 13]

x can be 0 or 1 depending on which half it is representing.

As long as many children fall in a contiguous range, we would be only needing 1 byte. Disadvantage to this approach :
a) even if 2 children exist in two different halves, we would have to fall back on 2 bytes of storage. 
b) 14,15 children can never be represented with one byte

Does this make sense? Do you think it is better/worse than your proposed approach?

2025-01-10 08:49 UTC, Scooletz commented on src/Paprika/Merkle/RlpMemo.cs
> -            var bits = leftover[^emptyBytesLength..];
What an interesting idea! One would need to count the collisions and probabilities 😅 

- for 2 nibbles, picking up two from one of the ranges is 7/15. 
- for 3 nibbles, we get 1/5
- for 4 nibbles, we get 1/13
- 
As we're trying to optimize for the small branches (the big won't benefit from removing 1 byte) it's a bet. With the ncoding proposed before, we get 1 byte for nibbles and always 2 bytes for other cases. Here we optimize up to any number, but this is diminishing returns, right? With 4 Keccaks it'll be only 1% saved.

What do you think then?

2025-01-10 08:50 UTC, Scooletz commented on src/Paprika.Tests/Merkle/RlpMemoTests.cs
> +    public void Random_delete()
I think I'd replace the Branch based test with a direct `KeccakMemo` test maybe? Not sure if covering the compounded Branch + memo is doable in a nice way.

2025-01-14 06:44 UTC, dipkakwani commented on src/Paprika/Merkle/RlpMemo.cs
> -        if (children.SetCount == 2 && (key.Path.Length + key.StoragePath.Length) % 2 == 0)
Good catch, I moved this code to `InspectBeforeApply`, since this optimization was done during compression, which we don't do now. But note that for this particular check, we now have to parse the branch data in `InspectBeforeApply` and then find out the `children.SetCount` value. Is the extra parsing in `InspectBeforeApply` still worth it to save off for small branches?

2025-01-14 06:45 UTC, dipkakwani commented on src/Paprika/Merkle/RlpMemo.cs
> -            var bits = leftover[^emptyBytesLength..];
I would like to take up this optimization in another PR, since it would require extra logic and even additional testing to ensure that it works fine.

2025-01-14 06:54 UTC, dipkakwani commented on src/Paprika/Merkle/RlpMemo.cs
> +            var bits = _buffer[^indexLength..];
I tried this particular change and for some reason it started breaking the `CalculateStateRootHash`. Tried bunch of ways to test/debug, but it wasn't clear what exactly was causing the test failure. Moving back to the original index at the end resolved the issues. 
Do you have any pointers if that is expected? But either way, I prefer to keep the underlying data consistent with the original representation after `Compress` operation, by keeping the index at the end and not deal with state root mismatch issues :sweat:

2025-01-14 06:58 UTC, dipkakwani commented on src/Paprika.Tests/Merkle/RlpMemoTests.cs
> +    public void Random_delete()
Added basic new tests in RLPMemo with fixed children. Branch + memo test couldn't be done without exposing few internal details as public, so sticking to independent unit tests.

2025-01-15 07:25 UTC, dipkakwani commented on src/Paprika/Merkle/RlpMemo.cs
> +            var bits = _buffer[^indexLength..];
As discussed offline, added new tests with grow/shrink which were able to catch the issue with header placement/incorrect implementation. Also modified the `Large_random_operations` test which caught failures too. The current coverage for RLPMemo class is 100%. All the test pass with the current implementation.

2025-01-15 12:24 UTC, Scooletz commented on src/Paprika/Merkle/RlpMemo.cs
> -            var bits = leftover[^emptyBytesLength..];
Having this said, should this PR be no longer labeled with `Breaking`?

2025-01-15 12:25 UTC, Scooletz commented on src/Paprika/Merkle/RlpMemo.cs
> +            var bits = _buffer[^indexLength..];
Massive.

2025-01-15 12:25 UTC, Scooletz reviewed
A few more clarifications.

2025-01-15 12:26 UTC, dipkakwani commented on src/Paprika/Merkle/RlpMemo.cs
> -            var bits = leftover[^emptyBytesLength..];
Yes, removed the label.

2025-01-15 12:31 UTC, dipkakwani commented on src/Paprika/Merkle/RlpMemo.cs
> -        if (children.SetCount == 2 && (key.Path.Length + key.StoragePath.Length) % 2 == 0)
I didn't get you fully.. we can save up that space, but I just wanted to point out that here we are doing an additional bit of parsing to find out the children count. I think that it is fine to be done for every branch, since we would be saving 64+2 bytes potentially with the smaller branches.

2025-01-15 12:44 UTC, Scooletz commented on src/Paprika/Merkle/RlpMemo.cs
> -        if (children.SetCount == 2 && (key.Path.Length + key.StoragePath.Length) % 2 == 0)
We are. This is due to the nature of unmaterialized data that need to be reparsed on each passing. I cannot provide you with numbers (#286 has none), but saving 66 bytes out of 68 for small branches seem to be a good deal 👀

2025-01-22 15:30 UTC, Scooletz approved these changes
Massive. The pool size speaks for itself. Let's merge in.

2025-01-22 15:30 UTC, merged